/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package thesis;

import java.util.Random;

public class App {
    
    private final static int ARRAY_SIZE = 100;
    private final static int MAX_RANDOM_VALUE = 1000;

    static Integer[] array = new Integer[ARRAY_SIZE];
    Random random = new Random();
    

    public App(){
        for (int i = 0; i<ARRAY_SIZE; i++) {
            array[i] = random.nextInt(MAX_RANDOM_VALUE);
        }
    }

    private void threads(Integer[] array) throws InterruptedException{

        Thread t1 = new Thread(() -> {
            //synchronized (lock) {
            try{
                MergeSort.sort(array);
            } catch (NullPointerException e) {
                throw new RuntimeException("Null due to race conditions", e);
            }
            //}
        });

        Thread t2 = new Thread(() -> {
            //synchronized (lock) {
            try{
                MergeSort.sort(array);
            } catch (NullPointerException e) {
                throw new RuntimeException("Null due to race conditions", e);
            }
            //};
        });

        Thread t3 = new Thread(() -> {
            //synchronized (lock) {
            try{
                MergeSort.sort(array);
            } catch (NullPointerException e) {
                throw new RuntimeException("Null due to race conditions", e);
            }
            //};
        });

        t1.start();
        t2.start();
        t3.start();
        t1.join();
        t2.join();
        t3.join();
    }

    private void toString(Integer[] array){
        for (Integer integer : array) {
            System.out.println(integer + " ");
        }

    }

    public static void main(String[] args) throws InterruptedException {
        
        App app = new App();
        app.threads(array);
        app.toString(array);
    }
}
