/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package thesis;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

public class AppTest {

}
